services:
  app:
    depends_on:
      db:
          condition: service_healthy
    links:
      - db

  db:
    image: postgres:17.0
    container_name: tgtime-api-db
    restart: always
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./init.sql:/docker/db/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      tgtime-api-network:
        aliases:
          - database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1s
  migrate:
    image: migrate/migrate
    networks:
      - tgtime-api-network
    volumes:
      - ./db/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db:${DATABASE_PORT}/${DATABASE_NAME}?sslmode=${DATABASE_SSL_MODE}", "up"]
    links:
      - db

volumes:
  data: