version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: officetime-api-app
    environment:
      - EXPOSE_PORT=${HTTP_PORT:-8081}
    ports:
      - "${HTTP_PORT:-8081}:8081"
      - "${GRPC_PORT:-8082}:8082"
    networks:
      - officetime-api-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${HTTP_PORT:-8081}/service/status"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 1s

networks:
  officetime-api-network:
    driver: bridge

volumes:
  data: