Env: 'dev'
HostName: db
HostPort: 5432
DataBaseName: 'officetime'
UserName: 'officetime'
Password: 'officetime'
SslMode: 'disable'
BotToken: ''
RouterAddress: ''
RouterUserName: ''
RouterPassword: ''
webHookPath: ''
TelegramBot: 'OfficeTimeTech'

AuthSigningKey: ''
AuthRefreshKey: ''
AuthAccessTokenExpires: 30 # minutes
AuthRefreshTokenExpires: 168 # hours