Env: 'dev'
HostName: 'localhost'
HostPort: 5432
DataBaseName: ''
UserName: ''
Password: ''
SslMode: 'disable'
BotToken: ''
RouterAddress: ''
RouterUserName: ''
RouterPassword: ''
webHookPath: ''
TelegramBot: ''

AuthSigningKey: ''
AuthRefreshKey: ''
AuthAccessTokenExpires: 30 # minutes
AuthRefreshTokenExpires: 168 # hours