name: Officetime-Api-Audit

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    audit:
        strategy:
            matrix:
                go-version: [1.21.x, 1.22.x]
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: ${{ matrix.go-version }}

            - name: Add config
              run: |
                touch ./.env
                echo ENV="dev" >> .env
                echo DATABASE_HOST="db" >> .env
                echo DATABASE_PORT="5432" >> .env
                echo DATABASE_NAME="officetime" >> .env
                echo DATABASE_USER="officetime" >> .env
                echo DATABASE_PASSWORD="officetime" >> .env
                echo DATABASE_SSL_MODE="disable" >> .env
                echo AUTH_SIGNING_KEY="vtlcgjgek" >> .env
                echo AUTH_REFRESH_KEY="vtlcgjgek" >> .env
                echo AUTH_ACCESS_TOKEN_EXPIRES="30" >> .env
                echo AUTH_REFRESH_TOKEN_EXPIRES="168" >> .env
                cat ./.env

            - name: Verify dependencies
              run: go mod verify

            - name: Build
              run: go build -v ./...

            - name: Run go vet
              run: go vet ./...