name: Officetime-Api-Test

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test:
        strategy:
            matrix:
                go-version: [1.21.x]
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: ${{ matrix.go-version }}

            - name: Add config
              run: cp ./config/config.example.yaml ./config/config.yaml

            - name: Start containers
              run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build

            - name: Health check
              run: docker run --network container:officetime-api-app-1 appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8080/ping